import { useEffect } from 'react';
import { TerminalPanel } from './TerminalPanel.jsx';
import { useVoice } from '../hooks/useVoice.js';
import { useChildSession } from '../hooks/useChildSession.js';
import { EVENING_CHIPS, MOODS, SEND_OFFS } from '../constants.js';
import { AppIcon, CompanionMascot } from '#web/shared/components/index.js';
import { MorningRipple } from './MorningRipple.jsx';
import { TalkToPip } from './TalkToPip.jsx';

export function ChildSession({ session, busy, notice, onSubmitTurn, onEnd, onExitTerminal, onCompleteMorning }) {
  const { text, setText, status, setStatus, morningStep, response, quest, messages, submit, submitTyped, chooseMood, chooseSendOff } = useChildSession({ session, busy, onSubmitTurn, onEnd });
  const { canRecognize, canSynthesize, isListening, isSpeaking, transcript, error, startListening, stopListening, speak } = useVoice({ onTranscript: (words) => submit(words, 'voice') });
  const voiceAllowed = session.settings?.voiceEnabled !== false;
  useEffect(() => { if (isListening) setStatus('listening'); else if (isSpeaking) setStatus('speaking'); else if (status === 'listening' || status === 'speaking') setStatus('idle'); }, [isListening, isSpeaking, status, setStatus]);
  const isMorning = session.sessionType === 'morning';
  if (isMorning && session.morning) return <MorningRipple session={session} busy={busy} notice={notice} onComplete={onCompleteMorning} onExit={() => onEnd('completed')} />;
  const isTerminal = status === 'safety-ended' || status === 'ended';
  if (session.mode === 'chat') return <TalkToPip messages={messages} text={text} setText={setText} status={status} busy={busy} canRecognize={canRecognize} canSynthesize={voiceAllowed && canSynthesize} isListening={isListening} isSpeaking={isSpeaking} transcript={transcript} error={error} startListening={startListening} stopListening={stopListening} speak={speak} onSubmit={submit} onSubmitTyped={submitTyped} onEnd={onEnd} terminal={isTerminal ? <TerminalPanel safety={status === 'safety-ended'} onReturn={onExitTerminal} /> : null} />;
  const indicator = status === 'listening' ? 'Listening...' : status === 'thinking' ? 'Thinking...' : status === 'speaking' ? 'Speaking...' : status === 'fallback' ? 'Try typing or tapping instead.' : status === 'completed' ? 'Morning complete' : status === 'safety-ended' ? 'This session is paused' : 'Ready when you are';
  const mascotMood = status === 'listening' ? 'listening' : status === 'thinking' ? 'thinking' : status === 'speaking' || status === 'completed' ? 'celebrating' : status === 'safety-ended' ? 'paused' : 'welcome';
  const isThinking = busy || status === 'thinking'; const controlsDisabled = busy || isThinking || isSpeaking; const activityLabel = isThinking ? 'Pip is following your idea...' : isListening ? 'Pip is listening. Take your time.' : 'Pip is reading this aloud.';
  return <section className="kid-shell" aria-label="Child session" aria-busy={isThinking || isListening || isSpeaking}>
    <header className="session-topline"><span>{isMorning ? 'Morning ripple' : quest?.title ?? 'Evening discovery'}</span><button type="button" className="session-exit" onClick={() => onEnd('child_exit')}>Save for later</button></header>
    <div className="session-hero"><div className="kid-copy"><p className="eyebrow">{isMorning ? 'Morning ripple' : quest?.stepLabel ?? 'Evening discovery'}</p><h1 className="font-display">{isMorning ? 'A tiny start is enough.' : quest?.title ?? 'Teach me one small thing.'}</h1><p className="status-line" aria-live="polite">{isThinking || isListening || isSpeaking ? indicator : quest?.progressMoment ?? indicator}</p></div><CompanionMascot mood={mascotMood} size="regular" decorative /></div>
    <article className={`companion-bubble ${isThinking ? 'is-thinking' : ''}`}><p>{response}</p><button type="button" className="sound-button" disabled={!voiceAllowed || !canSynthesize || controlsDisabled} onClick={() => speak(response)}><AppIcon name="volume" size="xs" decorative /> {isSpeaking ? 'Pip is speaking...' : voiceAllowed && canSynthesize ? 'Hear that again' : 'Text stays on screen'}</button></article>
    {(isThinking || isListening || isSpeaking) && <div className={`session-activity ${isThinking ? 'thinking' : isListening ? 'listening' : 'speaking'}`} role="status" aria-live="polite"><span className="activity-dots" aria-hidden="true"><i /><i /><i /></span><div><strong>{activityLabel}</strong><small>{isThinking ? 'Your controls will be ready in a moment.' : isListening ? (transcript || 'Say your idea, then Pip will take it from there.') : 'You can keep reading along on the screen.'}</small></div>{isListening && <button type="button" className="text-button" onClick={stopListening}>Stop listening</button>}</div>}
    {error && <p role="alert" className="voice-alert">{error}</p>}
    {isTerminal ? <TerminalPanel safety={status === 'safety-ended'} onReturn={onExitTerminal} /> : isMorning ? <div className="morning-controls">
      {morningStep === 'mood' && <><p className="control-title">How does your morning feel?</p><div className="tap-grid">{MOODS.map((option) => <button key={option} type="button" onClick={() => chooseMood(option)}>{option}</button>)}</div></>}
      {morningStep === 'sendoff' && <><p className="control-title">Pick a tiny send-off.</p><div className="tap-grid">{SEND_OFFS.map((option) => <button key={option} type="button" onClick={() => chooseSendOff(option)}>{option}</button>)}</div></>}
      {morningStep === 'complete' && <div className="completion-moment"><CompanionMascot mood="celebrating" size="small" decorative /><div><strong>You made a little space for yourself.</strong><p>That is a lovely way to begin.</p><button type="button" className="secondary-button" onClick={() => onEnd('child_exit')}>Finish for now</button></div></div>}
    </div> : <div className="evening-controls">{quest && <><div className="quest-progress" aria-label={`Quest step: ${quest.stepLabel}`}><span>{quest.stepLabel}</span><i /><i className={quest.step === 'try' || quest.step === 'reflect' || quest.step === 'finish' ? 'filled' : ''} /><i className={quest.step === 'reflect' || quest.step === 'finish' ? 'filled' : ''} /></div><p className="control-title">{quest.prompt}</p></>}{(quest?.choices ?? (session.mode === 'activity' ? ['Why does it happen?', 'What would change?', 'Show me an example'] : EVENING_CHIPS)).length > 0 && <div className="tap-row" aria-label="Quest choices">{(quest?.choices ?? (session.mode === 'activity' ? ['Why does it happen?', 'What would change?', 'Show me an example'] : EVENING_CHIPS)).map((chip) => <button key={chip} type="button" disabled={controlsDisabled} onClick={() => submit(chip, 'tap')}>{chip}</button>)}</div>}<form onSubmit={submitTyped} className="text-turn"><label className="field-label">{quest ? 'Teach Pip in your own words' : 'Or type what you learned'}<input value={text} onChange={(event) => setText(event.target.value)} placeholder={quest ? 'My idea is...' : 'I learned that...'} disabled={controlsDisabled} /></label><button disabled={controlsDisabled || !text.trim()} className="primary-button" type="submit">{quest?.step === 'finish' ? 'Name my keepsake' : 'Share it'}</button></form><div className="voice-row"><button type="button" className="mic-button" disabled={(!isListening && controlsDisabled) || !canRecognize} onClick={isListening ? stopListening : startListening}><AppIcon name="mic" size="sm" decorative /> {isListening ? 'Stop listening' : 'Talk instead'}</button><span>{canRecognize ? (transcript || 'Tap to speak. You can always type instead.') : 'Voice input is unavailable here. Type or tap instead.'}</span></div><button type="button" className="finish-link" disabled={controlsDisabled} onClick={() => onEnd(quest?.step === 'finish' ? 'completed' : 'child_exit')}>{quest?.step === 'finish' ? 'Keep this discovery' : 'Finish for now'}</button></div>}
  </section>;
}
