import { useEffect, useMemo, useState } from 'react';
import { AppIcon, CompanionMascot, StudentMark } from '#web/shared/components/index.js';
import { getMorningRipples, getRitualHome, getStudentReflections } from '../api/sessionApi.js';

const day = (value) => new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric' }).format(new Date(value));

export function StudentRitual({ student, busy, notice, onBegin }) {
  const [page, setPage] = useState('today');
  const [home, setHome] = useState(null);
  const [recaps, setRecaps] = useState([]);
  const [mornings, setMornings] = useState([]);
  const [selected, setSelected] = useState(null);
  const [error, setError] = useState('');
  const load = () => Promise.all([getRitualHome(student.id), getStudentReflections(student.id), getMorningRipples(student.id)]).then(([ritual, history, morningHistory]) => { setHome(ritual); setRecaps(history.recaps ?? []); setMornings(morningHistory.entries ?? []); setError(''); }).catch((issue) => setError(issue.message));
  useEffect(() => { load(); }, [student.id]);
  const moments = useMemo(() => [...mornings.map((entry) => ({ ...entry, kind: 'morning', when: entry.createdAt ?? entry.created_at })), ...recaps.map((entry) => ({ ...entry, kind: 'discovery', when: entry.createdAt ?? entry.created_at }))].sort((a, b) => new Date(b.when) - new Date(a.when)), [mornings, recaps]);
  if (error) return <section className="student-state"><p>{error}</p><button className="secondary-button" onClick={load}>Try again</button></section>;
  if (!home) return <section className="student-state" role="status">Pip is opening today's little world...</section>;
  const world = home.world ?? { theme: 'meadow', greeting: 'A fresh little world is waiting.', collectible: 'spark' };
  const learningHome = home.learningHome ?? { starters: [], review: null, currentKeepsake: null };
  const primaryName = home.recommendation.type === 'morning' ? 'Morning Ripple' : 'Evening Discovery';
  const begin = (type, mode = home.recommendation.mode, questId = null) => onBegin(type, mode, questId);
  const openReflection = async (sessionId) => { setSelected(await getStudentReflections(student.id, sessionId)); setPage('moments'); };
  return <section className={`student-world theme-${world.theme} age-band-${home.ageBand ?? 'explorer'}`} aria-label="Pip World">
    <header className="world-header"><div><p className="eyebrow">Pip World · today</p><p className="world-day">{world.greeting}</p></div><span className="world-token"><StudentMark name={world.collectible} size="md" label="Today's collectible" /></span></header>
    <main className="world-main">
      {page === 'today' && <>
        {notice && <p className="student-ritual-notice" role="status">{notice}</p>}
        <section className="today-hero"><div className="hero-orbit" aria-hidden="true"><i /><i /><i /></div><div className="today-copy"><p className="eyebrow">Pip's next idea</p><h1>Hi, {student.name}!</h1><p>{home.recommendation.reason}</p><button className="world-primary" disabled={busy} onClick={() => begin(home.recommendation.type)}><StudentMark name={home.recommendation.type === 'morning' ? 'morning' : 'discovery'} size="sm" decorative />Start {primaryName}<AppIcon name="arrow-right" size="sm" decorative /></button><small>A short moment is plenty. Nothing to catch up on.</small></div><CompanionMascot mood="welcome" size="hero" decorative /></section>
        <p className="student-helper-note"><AppIcon name="info" size="xs" decorative /> Pip is a learning helper. It asks curious questions—it is not a person or a judge.</p>
        {learningHome.currentKeepsake && <section className="return-card"><StudentMark name={learningHome.currentKeepsake.collectible ?? learningHome.currentKeepsake.discovery ?? 'spark'} size="md" decorative /><div><p className="eyebrow">A little thread to carry</p><strong>{learningHome.currentKeepsake.intention ?? learningHome.currentKeepsake.title}</strong><small>Come back whenever you want to grow another idea.</small></div></section>}
        <section className="world-section quest-shelf"><div className="section-heading"><div><p className="eyebrow">Choose a Pip Quest</p><h2>What should Pip wonder about?</h2></div><span>3–5 minutes</span></div><div className="quest-starter-grid">{learningHome.starters.map((quest) => <button key={quest.id} disabled={busy} onClick={() => begin('evening', 'quest', quest.id)}><StudentMark name={quest.collectible} size="md" decorative /><strong>{quest.title}</strong><small>{quest.topic}</small></button>)}</div>{learningHome.review && <button className="review-quest" disabled={busy} onClick={() => begin('evening', 'quest', learningHome.review.questId)}><StudentMark name="sunbeam" size="md" decorative /><span><strong>{learningHome.review.title}</strong><small>{learningHome.review.copy}</small></span><AppIcon name="arrow-right" size="sm" decorative /></button>}</section>
        <section className="world-alternates" aria-label="Other rituals"><button onClick={() => begin('morning')} disabled={busy}><StudentMark name="morning" size="md" decorative /><div><strong>Morning Ripple</strong><small>Arrive, choose, launch</small></div><AppIcon name="arrow-right" size="sm" decorative /></button><button onClick={() => begin('evening', 'chat')} disabled={busy}><StudentMark name="cloud" size="md" decorative /><div><strong>Talk to Pip</strong><small>Bring any safe question</small></div><AppIcon name="arrow-right" size="sm" decorative /></button></section>
      </>}
      {page === 'world' && <section className="world-collection"><p className="eyebrow">Your growing place</p><h1>Small ideas leave a trail.</h1><p className="collection-intro">Every launch card and discovery becomes a calm little keepsake. There are no scores or streaks here.</p><div className="collection-sky"><StudentMark name={world.collectible} size="xl" decorative /><StudentMark name="cloud" size="lg" decorative /><StudentMark name="spark" size="md" decorative /><CompanionMascot mood="thinking" size="small" decorative /></div><div className="collection-grid"><article><StudentMark name="morning" size="md" decorative /><strong>{mornings.length}</strong><small>morning cards</small></article><article><StudentMark name="discovery" size="md" decorative /><strong>{recaps.length}</strong><small>discoveries</small></article><article><StudentMark name="world" size="md" decorative /><strong>{moments.length}</strong><small>keepsakes</small></article></div></section>}
      {page === 'moments' && <section className="moments-page"><p className="eyebrow">Your timeline</p><h1>My Moments</h1>{selected ? <article className="moment-detail"><button className="text-button" onClick={() => setSelected(null)}><AppIcon name="arrow-left" size="xs" decorative />Back to moments</button><h2>{selected.recap?.title}</h2><p>{selected.recap?.summary}</p>{selected.turns.map((turn, index) => <p className={`reflection-turn ${turn.role}`} key={index}><strong>{turn.role === 'child' ? 'You' : 'Pip'}</strong>{turn.text}</p>)}</article> : <div className="moment-timeline">{moments.length ? moments.map((moment) => <button key={`${moment.kind}-${moment.id ?? moment.sessionId}`} onClick={() => moment.kind === 'discovery' && openReflection(moment.sessionId)}><span className={`moment-icon ${moment.kind}`}><StudentMark name={moment.kind === 'morning' ? moment.collectible : moment.discovery} size="sm" decorative /></span><div><small>{moment.kind === 'morning' ? 'Morning launch' : 'Discovery'} · {day(moment.when)}</small><strong>{moment.kind === 'morning' ? moment.intention : moment.title}</strong><p>{moment.kind === 'morning' ? moment.activityResult || 'You chose a small direction for your day.' : moment.summary}</p></div>{moment.kind === 'discovery' && <AppIcon name="arrow-right" size="sm" decorative />}</button>) : <div className="empty-moments"><StudentMark name="discovery" size="lg" decorative /><h2>Your first moment is waiting.</h2><button className="secondary-button" onClick={() => setPage('today')}>See today</button></div>}</div>}</section>}
    </main>
    <nav className="world-bottom-nav" aria-label="Student navigation"><button aria-current={page === 'today' ? 'page' : undefined} className={page === 'today' ? 'active' : ''} onClick={() => { setPage('today'); setSelected(null); }}><StudentMark name="morning" size="sm" decorative />Today</button><button aria-current={page === 'world' ? 'page' : undefined} className={page === 'world' ? 'active' : ''} onClick={() => { setPage('world'); setSelected(null); }}><StudentMark name="world" size="sm" decorative />World</button><button aria-current={page === 'moments' ? 'page' : undefined} className={page === 'moments' ? 'active' : ''} onClick={() => setPage('moments')}><StudentMark name="moments" size="sm" decorative />My Moments</button></nav>
  </section>;
}
