import { useEffect, useState } from 'react';
import { AppIcon, CompanionMascot, StudentMark } from '#web/shared/components/index.js';
import heroFieldGuide from '#web/assets/landing-field-guide-hero.jpg';
import trailFieldGuide from '#web/assets/landing-field-guide-trail.jpg';

const navigation = [['the-trail', 'The trail'], ['inside', 'Inside'], ['for-parents', 'For parents'], ['questions', 'Questions']];
const moments = [['01', 'They notice', 'A small invitation begins with the real world: a shell, a shadow, a question from the walk home.'], ['02', 'Pip stays curious', 'Pip gives their idea room. It asks a friendly follow-up instead of supplying the answer.'], ['03', 'You have an opening', 'You receive one warm conversation starter—context for connection, never a report card.']];
const promises = [['device', 'Parent-approved devices', 'A child enters on a device you have set up and can revoke whenever you need.'], ['message', 'A learning helper, not a friend', 'Pip is here to support curiosity. It is not a therapist, confidant, or judge.'], ['trail', 'No scores to chase', 'No streaks, rankings, mastery claims, or pressure. A meaningful moment is enough.']];
const faqs = [['What does my child see?', 'One gentle suggested ritual, with other permitted choices always visible. The experience changes with the learning stage you choose.'], ['What does a parent see?', 'A calm Today view, family rhythm, approved devices, and conversation starters—not grades or a performance dashboard.'], ['How do you handle privacy?', 'Your family controls transcript access and optional product-improvement analytics. Safety-triggering text is not shown in the parent view or used by Pip.'], ['Is this another thing to keep up with?', 'No. Undercurrent is designed around one small moment, when it fits. There is nothing to catch up on.']];

function scrollToSection(id) { document.getElementById(id)?.scrollIntoView({ behavior: 'smooth', block: 'start' }); }
function FieldStamp({ children, className = '' }) { return <span className={`fg-stamp ${className}`.trim()}>{children}</span>; }

export function LandingPage({ onGetStarted, onSignIn, onExplore }) {
  const [menuOpen, setMenuOpen] = useState(false);
  const signIn = onSignIn ?? onGetStarted;
  useEffect(() => { const closeOnEscape = (event) => { if (event.key === 'Escape') setMenuOpen(false); }; window.addEventListener('keydown', closeOnEscape); return () => window.removeEventListener('keydown', closeOnEscape); }, []);
  const visit = (id) => { setMenuOpen(false); scrollToSection(id); };
  const explore = () => { onExplore?.(); visit('the-trail'); };
  return <main className="field-guide-landing">
    <nav className="fg-nav" aria-label="Landing page">
      <a className="fg-nav-mark" href="#top" onClick={(event) => { event.preventDefault(); visit('top'); }} aria-label="Undercurrent home"><AppIcon name="logo" size="sm" decorative /> Undercurrent</a>
      <div className="fg-nav-desktop">{navigation.map(([id, label]) => <a href={`#${id}`} key={id}>{label}</a>)}</div>
      <div className="fg-nav-actions"><button className="fg-sign-in" type="button" onClick={signIn}>Parent sign in</button><button className="fg-nav-setup" type="button" onClick={onGetStarted}>Start setup <AppIcon name="arrow-right" size="xs" decorative /></button><button className="fg-menu-button" type="button" aria-label={menuOpen ? 'Close page navigation' : 'Open page navigation'} aria-expanded={menuOpen} aria-controls="field-guide-mobile-nav" onClick={() => setMenuOpen((open) => !open)}><AppIcon name={menuOpen ? 'close' : 'menu'} size="sm" decorative /></button></div>
      <div id="field-guide-mobile-nav" className={`fg-mobile-menu ${menuOpen ? 'is-open' : ''}`} hidden={!menuOpen}>{navigation.map(([id, label]) => <a href={`#${id}`} key={id} onClick={(event) => { event.preventDefault(); visit(id); }}>{label}</a>)}<button type="button" onClick={signIn}>Parent sign in</button><button type="button" onClick={onGetStarted}>Start parent setup <AppIcon name="arrow-right" size="xs" decorative /></button></div>
    </nav>
    <section id="top" className="fg-hero" aria-labelledby="landing-title"><div className="fg-hero-copy"><FieldStamp>Field notes for curious families</FieldStamp><p className="fg-kicker">A family curiosity trail</p><h1 id="landing-title">Make room for <em>little wonders.</em></h1><p className="fg-lede">Undercurrent gives children a small place to teach Pip something from their day—and gives you a calm way to stay in the loop.</p><div className="fg-hero-actions"><button className="fg-primary-button" type="button" onClick={onGetStarted}>Start parent setup <AppIcon name="arrow-right" size="sm" decorative /></button><button className="fg-secondary-button" type="button" onClick={explore}>See one small moment <AppIcon name="arrow-down" size="sm" decorative /></button></div><ul className="fg-trust-chips" aria-label="Undercurrent promises"><li>Parent-visible by design</li><li>No scores</li><li>Nothing to catch up on</li></ul></div><div className="fg-hero-art"><div className="fg-contour fg-contour-one" aria-hidden="true"><span>Look<br />closer</span></div><div className="fg-contour fg-contour-two" aria-hidden="true"><span>Find one<br />small thing</span></div><img src={heroFieldGuide} alt="A child and Pip exploring a field-guide map in a wildflower meadow" /><FieldStamp className="fg-hero-stamp">Small things count</FieldStamp></div></section>
    <section id="the-trail" className="fg-moment" aria-labelledby="trail-title"><div className="fg-section-intro"><FieldStamp>One small moment</FieldStamp><p className="fg-kicker">The trail, from their side to yours</p><h2 id="trail-title">A child’s curiosity can become a family conversation.</h2><p>Not a checklist. Not a lesson plan. Just a tiny trail that starts with what they notice and lands in a question you can share.</p></div><div className="fg-moment-layout"><ol className="fg-story-path">{moments.map(([number, title, copy]) => <li key={number}><span className="fg-story-number">{number}</span><div><h3>{title}</h3><p>{copy}</p></div></li>)}</ol><figure className="fg-trail-art"><img src={trailFieldGuide} alt="A field-guide illustration showing a child’s discovery, Pip’s curious question, and a warm parent-child conversation" /><figcaption><AppIcon name="trail" size="sm" decorative /> A ritual that travels from their world to yours.</figcaption></figure></div></section>
    <section id="inside" className="fg-inside" aria-labelledby="inside-title"><div className="fg-section-intro fg-section-intro-light"><FieldStamp>Inside Undercurrent</FieldStamp><p className="fg-kicker">Two views, one family rhythm</p><h2 id="inside-title">A quiet corner for them. Clear context for you.</h2></div><div className="fg-product-frames"><article className="fg-device fg-device-student"><div className="fg-device-top"><span>Today with Pip</span><span>Morning</span></div><div className="fg-pip-orbit"><CompanionMascot mood="welcome" size="large" decorative /><StudentMark name="spark" size="sm" decorative /><StudentMark name="spark" size="sm" decorative /></div><p className="fg-device-label">A tiny invitation</p><h3>What tiny thing might you teach Pip about today?</h3><button type="button" onClick={onGetStarted}>Begin a small moment <AppIcon name="arrow-right" size="xs" decorative /></button><p className="fg-device-note">One small moment is plenty.</p></article><article className="fg-device fg-device-parent"><div className="fg-device-top"><span>Family field journal</span><span className="fg-private-dot"><AppIcon name="lock" size="xs" decorative /> Private</span></div><div className="fg-parent-card"><p>Today’s opening</p><strong>“What would you like to show Pip about that?”</strong></div><div className="fg-parent-rhythm"><span>Family rhythm</span><b>Gentle · 1 moment</b><i><span /></i></div><div className="fg-parent-keep"><StudentMark name="spark" size="sm" decorative /><div><p>A keepsake, not a score</p><small>Notice the ideas worth returning to.</small></div></div></article></div></section>
    <section id="for-parents" className="fg-parent-promise" aria-labelledby="promise-title"><div className="fg-promise-copy"><FieldStamp>Designed for the grown-up</FieldStamp><p className="fg-kicker">Calm clarity, built in</p><h2 id="promise-title">The boundaries are part of the welcome.</h2><p>You choose the rhythm, the device, and the access. Your child gets a learning space that feels open, never performative.</p><button className="fg-inline-link" type="button" onClick={onGetStarted}>See how parent setup works <AppIcon name="arrow-right" size="xs" decorative /></button></div><div className="fg-promise-list">{promises.map(([icon, title, copy]) => <article key={title}><AppIcon name={icon} size="md" decorative /><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div></section>
    <section className="fg-how" aria-labelledby="how-title"><div className="fg-section-intro"><FieldStamp>How it works</FieldStamp><h2 id="how-title">Three gentle steps, then the trail is theirs.</h2></div><div className="fg-how-grid"><article><span>01</span><div className="fg-how-doodle" aria-hidden="true"><AppIcon name="trail" size="lg" decorative /></div><h3>Set the trail</h3><p>Add your child, choose a rhythm, and preview their world.</p></article><article><span>02</span><div className="fg-how-doodle" aria-hidden="true"><AppIcon name="device" size="lg" decorative /></div><h3>Hand over the device</h3><p>Use a simple PIN here or invite another approved device.</p></article><article><span>03</span><div className="fg-how-doodle" aria-hidden="true"><AppIcon name="message" size="lg" decorative /></div><h3>Follow the opening</h3><p>Let their discoveries make a little more room for conversation.</p></article></div></section>
    <section id="questions" className="fg-faq" aria-labelledby="faq-title"><div className="fg-faq-heading"><FieldStamp>Clear answers</FieldStamp><h2 id="faq-title">Questions parents usually ask.</h2><p>Everything begins with parent setup. No surprise child account, no hidden pressure.</p></div><div className="fg-faq-list">{faqs.map(([question, answer], index) => <details key={question} open={index === 0}><summary>{question}<AppIcon name="chevron-down" size="sm" decorative /></summary><p>{answer}</p></details>)}</div></section>
    <section className="fg-final-cta" aria-labelledby="final-title"><div><FieldStamp>Ready when you are</FieldStamp><h2 id="final-title">Begin with one curious child and one gentle moment.</h2><p>Set up the family trail in a few calm steps. You stay in control all the way.</p></div><div className="fg-final-actions"><button className="fg-primary-button" type="button" onClick={onGetStarted}>Start parent setup <AppIcon name="arrow-right" size="sm" decorative /></button><button className="fg-final-signin" type="button" onClick={signIn}>Already a parent? Sign in</button></div></section>
    <footer className="fg-footer"><div><a className="fg-footer-mark" href="#top" onClick={(event) => { event.preventDefault(); visit('top'); }}><AppIcon name="logo" size="sm" decorative /> Undercurrent</a><p>Small rituals for the curious life of a family.</p></div><nav aria-label="Footer navigation">{navigation.map(([id, label]) => <a href={`#${id}`} key={id} onClick={(event) => { event.preventDefault(); visit(id); }}>{label}</a>)}<button type="button" onClick={signIn}>Parent sign in</button></nav><p className="fg-footer-note">Parent-visible by design. Built for curiosity, not performance.</p></footer>
  </main>;
}
