import { createHash } from 'node:crypto';
import { AppError } from '#api/shared/errors/appError.js';
import { checkSafety, containsPersonalContact, safetyRedirect } from '#api/modules/safety/safetyCheck.js';
import { nextScaffoldStage } from '#api/modules/learning/scaffolding.js';
import { reconcileAssessments } from '#api/modules/learning/calibration.js';
import { nextReview } from '#api/modules/learning/scheduler.js';
import { effortWin } from '#api/modules/learning/rewards.js';
import { questFor, questStarters, questState } from '#api/modules/learning/questCatalog.js';

const requestHash = (input) => createHash('sha256').update(input).digest('hex');
const sessionMode = (session) => (session.questId ?? session.quest_id) === 'talk-to-pip' ? 'chat' : 'quest';
const utcDate = (value) => value.toISOString().slice(0, 10);
const defaults = { morningStartHour: 5, eveningStartHour: 16, dailySessionLimit: 2, voiceEnabled: true, activityEnabled: true, preferredStyle: 'adaptive', morningAiEnabled: false, morningPaths: 'energy,ready,calm,curiosity,reflect', morningSensitivity: 'standard', experienceBandOverride: null };
const settingsFor = (value) => ({ ...defaults, ...(value ?? {}) });
export const ageBandForGrade = (grade) => {
  const normalized = String(grade ?? '').trim().toLowerCase();
  const numeric = Number.parseInt(normalized.replace(/^grade\s*/, ''), 10);
  if (['pre-k', 'prek', 'kindergarten', 'k'].includes(normalized) || (Number.isInteger(numeric) && numeric <= 2)) return 'early';
  if (Number.isInteger(numeric) && numeric >= 7) return 'independent';
  return 'explorer';
};
export const effectiveAgeBand = (grade, settings) => settings?.experienceBandOverride ?? ageBandForGrade(grade);
const recapFor = (type, session = {}) => type === 'morning' ? { title: 'A gentle start', summary: 'You made a little space to notice how your day feels.', discovery: 'sunrise' } : (() => { const quest = questFor({ questId: session.questId ?? session.quest_id, mode: session.mode }); return { title: quest.title, summary: `You helped Pip explore ${quest.topic} in your own words.`, discovery: quest.collectible }; })();
const morningDeck = [
  { id: 'sun-stretch', path: 'energy', prompt: 'Make a tiny sun shape with your arms, then choose one thing you are ready to try.', collectible: 'sunbeam', theme: 'sunrise', activity: { kind: 'move', choices: ['Stretch tall', 'Shake out my hands', 'Take three slow steps'] } },
  { id: 'backpack-plan', path: 'ready', prompt: 'Pick the first small thing that will help your day feel ready.', collectible: 'compass', theme: 'sky', activity: { kind: 'plan', choices: ['Pack one thing', 'Choose my first step', 'Ask for help if I need it'] } },
  { id: 'cloud-breath', path: 'calm', prompt: 'Trace a slow cloud in the air and choose what would help you feel steady.', collectible: 'cloud', theme: 'mist', activity: { kind: 'notice', choices: ['Find a soft color', 'Listen for one sound', 'Take one slow breath'] } },
  { id: 'wonder-spark', path: 'curiosity', prompt: 'Choose something you would love to notice or ask about today.', collectible: 'spark', theme: 'citrus', activity: { kind: 'wonder', choices: ['Something outside', 'Something at school', 'Something I use'] } },
  { id: 'kind-start', path: 'reflect', prompt: 'Choose one kind thing you can offer yourself or someone else today.', collectible: 'leaf', theme: 'meadow', activity: { kind: 'kindness', choices: ['Use kind words', 'Give myself time', 'Notice someone helpful'] } }
];
const morningPlan = (studentId, settings, recent = [], band = 'explorer') => { const allowed = settings.morningPaths.split(',').filter(Boolean); const recentIds = recent.map((entry) => entry.activityId ?? entry.activity_id); const lastMood = recent.at(-1)?.mood; const allowedDeck = morningDeck.filter((item) => allowed.includes(item.path)); const calmFirst = ['heavy', 'sleepy'].includes(lastMood) ? allowedDeck.filter((item) => item.path === 'calm') : []; const choices = calmFirst.length ? calmFirst : allowedDeck.filter((item) => !recentIds.includes(item.id)); const pool = choices.length ? choices : allowedDeck; const index = Math.abs([...studentId].reduce((total, char) => total + char.charCodeAt(0), new Date().getDate())) % pool.length; const selected = pool[index] ?? morningDeck[0]; return { ...selected, activity: { ...selected.activity, prompt: band === 'early' ? 'Choose one tiny thing to try.' : selected.prompt } }; };
const dailyWorld = (studentId, current = new Date()) => {
  const key = utcDate(current); const seed = [...`${studentId}-${key}`].reduce((total, char) => (total * 31 + char.charCodeAt(0)) >>> 0, 7);
  const worlds = [
    { theme: 'meadow', greeting: 'The meadow has a new tiny path today.', collectible: 'leaf' },
    { theme: 'sky', greeting: 'A bright little idea is floating nearby.', collectible: 'compass' },
    { theme: 'mist', greeting: 'A quiet cloud is making room to wonder.', collectible: 'cloud' },
    { theme: 'citrus', greeting: 'Something sunny and curious is ready.', collectible: 'spark' },
    { theme: 'sunrise', greeting: 'A warm spark is ready to travel with you.', collectible: 'sunbeam' }
  ];
  return { ...worlds[seed % worlds.length], dayKey: key };
};

export function buildCuriosityTrail(completedSessions, now = new Date()) {
  const today = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate())); const completedDates = new Set(completedSessions.map((session) => utcDate(new Date(session.endedAt ?? session.ended_at))));
  return Array.from({ length: 7 }, (_value, index) => { const date = new Date(today); date.setUTCDate(today.getUTCDate() - 6 + index); const value = utcDate(date); return { date: value, completed: completedDates.has(value) }; });
}

export function createSessionsService({ repositories, agents = null, encryption = null, config = { aiDailyTurnLimit: 24, disableDailyRitualLimit: true }, notifySafety = async () => undefined, now = () => new Date() }) {
  async function authorize(parent, studentId) { if (parent.student_id && parent.student_id !== studentId) throw new AppError(403, 'ACCESS_DENIED', 'This student device cannot open another student profile.'); const student = await repositories.canAccessStudent({ householdId: parent.household_id, studentId }); if (!student) throw new AppError(403, 'ACCESS_DENIED', 'That child profile is not available in this household.'); if (student.consent_status !== 'granted') throw new AppError(403, 'CONSENT_REQUIRED', 'Parent consent is required before using this child profile.'); return student; }
  async function runTurn({ parent, student, session, sessionId, input }) {
    const safety = checkSafety(input); if (safety.triggered) { await repositories.createSafetyEvent({ studentId: student.id, sessionId, category: safety.category }); await repositories.endSession(sessionId, 'safety'); const alertParent = parent.email ? parent : repositories.findParentByHousehold ? await repositories.findParentByHousehold(parent.household_id) : parent; try { await notifySafety({ parent: alertParent ?? parent, student, category: safety.category }); } catch { /* The child redirect must not depend on notification delivery. */ } return { message: safetyRedirect, terminal: true, parentNotification: true }; }
    if (containsPersonalContact(input)) return { message: 'Please do not share contact details here. Tell a trusted grown-up if you need help.', terminal: false, parentNotification: false };
    if (session.type === 'morning') return { message: 'Pick a feeling or a send-off to keep this morning light.', terminal: false };
    if (Date.now() - new Date(session.startedAt ?? session.started_at).getTime() > 480000 || (session.turnCount ?? session.turn_count ?? 0) >= 6) { await repositories.endSession(sessionId, 'session_cap'); const quest = questFor({ questId: session.questId ?? session.quest_id, mode: session.mode }); return { message: 'That is enough for today. Your idea can rest here until next time.', terminal: true, questState: questState({ quest, turnCount: 3 }) }; }
    if (!agents || !encryption) throw new AppError(503, 'AI_UNAVAILABLE', 'The learning helper is temporarily unavailable. Please try again soon.');
    const encrypted = encryption.encrypt(input); await repositories.addSessionTurn({ sessionId, role: 'child', ...encrypted });
    try { const [first, second] = await Promise.all([agents.assess(input, 'Focus on conceptual completeness.'), agents.assess(input, 'Independently estimate confidence from the wording.')]); const assessment = reconcileAssessments(first, second); const stage = nextScaffoldStage(session.scaffoldStage ?? session.scaffold_stage, assessment); const turnCount = (session.turnCount ?? session.turn_count ?? 0) + 1; const message = await agents.compose({ input, scaffoldStage: stage, turnCount }); const topic = await repositories.upsertTopic({ studentId: student.id, label: assessment.topic, review: nextReview({ understanding: assessment.understanding }) }); await repositories.addScore({ sessionId, topicId: topic.id, understanding: assessment.understanding, confidence: assessment.confidence, gapLabel: assessment.gapLabel, assessorAgreement: first.understanding === second.understanding ? 1 : 0 }); const win = effortWin({ turnCount, scaffoldStage: stage, disengaged: assessment.disengaged }); if (win) await repositories.addWin({ studentId: student.id, sessionId, ...win }); const quest = questFor({ questId: session.questId ?? session.quest_id, mode: session.mode, studentId: student.id }); const state = questState({ quest, turnCount, scaffoldStage: stage }); await repositories.updateSessionProgress(sessionId, { turnCount, scaffoldStage: stage, questStep: state.step }); await repositories.addSessionTurn({ sessionId, role: 'companion', ...encryption.encrypt(message) }); return { message, terminal: false, questState: state, nextAction: state.step, choices: state.choices, progressMoment: state.progressMoment }; } catch (error) { if (error instanceof AppError) throw error; throw new AppError(503, 'AI_UNAVAILABLE', 'The learning helper is temporarily unavailable. Please try again soon.'); }
  }
  return Object.freeze({
    async home(parent, studentId) { const student = await authorize(parent, studentId); const settings = settingsFor(await repositories.getRitualSettings(studentId)); const band = effectiveAgeBand(student.grade, settings); const current = now(); const hour = current.getHours(); const type = hour >= settings.eveningStartHour ? 'evening' : 'morning'; const modes = ['quest', 'chat', ...(settings.activityEnabled ? ['activity'] : [])]; const adaptive = band === 'early' && settings.activityEnabled ? 'activity' : 'quest'; const mode = settings.preferredStyle === 'adaptive' ? adaptive : (modes.includes(settings.preferredStyle) ? settings.preferredStyle : 'quest'); const morning = repositories.listMorningRipples ? await repositories.listMorningRipples(studentId) : []; const recaps = repositories.listRecaps ? await repositories.listRecaps(studentId) : []; const topics = repositories.listTopics ? await repositories.listTopics(studentId) : []; const world = dailyWorld(studentId, current); const review = topics.find((topic) => topic.nextReviewAt && new Date(topic.nextReviewAt) <= current); return { settings, ageBand: band, world, modes, routine: { phase: type, remainingToday: config.disableDailyRitualLimit ? 99 : Math.max(0, settings.dailySessionLimit - (await repositories.listCompletedSessions(studentId, { from: new Date(Date.UTC(current.getUTCFullYear(), current.getUTCMonth(), current.getUTCDate())), to: new Date(Date.UTC(current.getUTCFullYear(), current.getUTCMonth(), current.getUTCDate() + 1)) })).length), recentMorningActivityIds: morning.slice(-4).map((entry) => entry.activityId ?? entry.activity_id) }, recommendation: { type, mode, reason: type === 'morning' ? 'A tiny start can make room for the day.' : 'One small idea is enough for tonight.' }, learningHome: { starters: questStarters(), review: review ? { questId: `review:${review.label}`, title: 'Remember & remix', copy: `Give ${review.label} a new example.` } : null, currentKeepsake: morning.at(-1) ?? recaps.at(-1) ?? null } }; },
    async start(parent, { studentId, type = 'evening', mode = 'quest', questId = null }) { const student = await authorize(parent, studentId); const settings = settingsFor(await repositories.getRitualSettings(studentId)); const band = effectiveAgeBand(student.grade, settings); const current = now(); const from = new Date(Date.UTC(current.getUTCFullYear(), current.getUTCMonth(), current.getUTCDate())); const to = new Date(Date.UTC(current.getUTCFullYear(), current.getUTCMonth(), current.getUTCDate() + 1)); if (!config.disableDailyRitualLimit && (await repositories.listCompletedSessions(studentId, { from, to })).length >= settings.dailySessionLimit) throw new AppError(429, 'DAILY_RITUAL_LIMIT', 'That is enough for today. Your next little moment will be here tomorrow.'); if (mode === 'activity' && !settings.activityEnabled) throw new AppError(403, 'ACTIVITY_DISABLED', 'Tiny activities are not available for this ritual.'); const recent = repositories.listMorningRipples ? (await repositories.listMorningRipples(studentId)).slice(-4) : []; const morning = type === 'morning' ? morningPlan(studentId, settings, recent, band) : null; const quest = type === 'evening' ? questFor({ questId, mode, studentId }) : null; const session = await repositories.createSession({ studentId, type, questId: quest?.id ?? null, questStep: quest ? 'spark' : null }); const openingPrompt = type === 'morning' ? `Pip here! ${morning.prompt}` : quest.opening; return { sessionId: session.id, sessionType: type, mode, openingPrompt, settings, ageBand: band, morning, quest: quest ? questState({ quest }) : null }; },
    async getCuriosityTrail(parent, studentId) { await authorize(parent, studentId); const current = now(); const from = new Date(Date.UTC(current.getUTCFullYear(), current.getUTCMonth(), current.getUTCDate() - 6)); const to = new Date(Date.UTC(current.getUTCFullYear(), current.getUTCMonth(), current.getUTCDate() + 1)); return { days: buildCuriosityTrail(await repositories.listCompletedSessions(studentId, { from, to }), current) }; },
    async end(parent, { sessionId, reason = 'child_exit' }) { const session = await repositories.getSession(sessionId); if (!session) throw new AppError(404, 'SESSION_NOT_FOUND', 'Choose a valid session first.'); await authorize(parent, session.studentId ?? session.student_id); await repositories.endSession(sessionId, reason); if (reason !== 'safety' && (session.type === 'morning' || (session.turnCount ?? session.turn_count ?? 0) > 0)) await repositories.createRecap({ sessionId, studentId: session.studentId ?? session.student_id, ...recapFor(session.type, session) }); return { ok: true }; },
    async history(parent, studentId, sessionId = null) { await authorize(parent, studentId); const recaps = await repositories.listRecaps(studentId); if (!sessionId) return { recaps: recaps.slice().reverse() }; const session = await repositories.getSession(sessionId); if (!session || (session.studentId ?? session.student_id) !== studentId || session.endReason === 'safety') throw new AppError(404, 'REFLECTION_NOT_FOUND', 'That reflection is not available.'); return { recap: recaps.find((item) => item.sessionId === sessionId) ?? null, turns: encryption ? (await repositories.listSessionTurns(sessionId)).map((turn) => ({ role: turn.role, text: encryption.decrypt(turn) })) : [] }; },
    async conversations(parent, studentId) { await authorize(parent, studentId); const rows = await repositories.listParentConversations(studentId); return { conversations: rows.map((session) => ({ id: session.id, type: session.type, mode: sessionMode(session), questId: session.questId ?? session.quest_id, startedAt: session.startedAt ?? session.started_at, endedAt: session.endedAt ?? session.ended_at, endReason: session.endReason ?? session.end_reason, turnCount: session.turnCount ?? session.turn_count ?? 0, live: !(session.endedAt ?? session.ended_at) })) }; },
    async conversation(parent, studentId, sessionId) { await authorize(parent, studentId); const session = await repositories.getSession(sessionId); if (!session || (session.studentId ?? session.student_id) !== studentId || (session.endReason ?? session.end_reason) === 'safety') throw new AppError(404, 'CONVERSATION_NOT_FOUND', 'That conversation is not available.'); if (!encryption) throw new AppError(503, 'CONVERSATION_UNAVAILABLE', 'Conversation history is temporarily unavailable.'); return { conversation: { id: session.id, type: session.type, mode: sessionMode(session), questId: session.questId ?? session.quest_id, startedAt: session.startedAt ?? session.started_at, endedAt: session.endedAt ?? session.ended_at, endReason: session.endReason ?? session.end_reason, live: !(session.endedAt ?? session.ended_at) }, turns: (await repositories.listSessionTurns(sessionId)).map((turn) => ({ id: turn.id, role: turn.role, text: encryption.decrypt(turn), createdAt: turn.createdAt ?? turn.created_at })) }; },
    async getSettings(parent, studentId) { const student = await authorize(parent, studentId); const settings = settingsFor(await repositories.getRitualSettings(studentId)); return { ...settings, effectiveAgeBand: effectiveAgeBand(student.grade, settings) }; },
    async morningHistory(parent, studentId) { await authorize(parent, studentId); return { entries: (await repositories.listMorningRipples(studentId)).slice().reverse() }; },
    async completeMorning(parent, body) { const session = await repositories.getSession(body.sessionId); if (!session || session.type !== 'morning') throw new AppError(404, 'MORNING_SESSION_NOT_FOUND', 'Open a morning ripple first.'); const studentId = session.studentId ?? session.student_id; await authorize(parent, studentId); const allowedPaths = settingsFor(await repositories.getRitualSettings(studentId)).morningPaths.split(','); if (!allowedPaths.includes(body.path)) throw new AppError(403, 'MORNING_PATH_DISABLED', 'That morning path is unavailable.'); const activity = morningDeck.find((item) => item.id === body.activityId && item.path === body.path); if (!activity || !['steady', 'curious', 'sleepy', 'wiggly', 'bright', 'heavy'].includes(body.mood) || !['low', 'medium', 'high'].includes(body.energy) || !body.intention?.trim()) throw new AppError(400, 'VALIDATION_ERROR', 'Complete each morning ripple step.'); const entry = await repositories.createMorningRipple({ studentId, sessionId: body.sessionId, mood: body.mood, energy: body.energy, path: body.path, activityId: activity.id, activityResult: body.activityResult?.slice(0, 280) ?? null, intention: body.intention.trim().slice(0, 140), theme: activity.theme, collectible: activity.collectible, contentSource: 'curated', prompt: activity.prompt }); return { entry: entry ?? { activityId: activity.id, collectible: activity.collectible, theme: activity.theme } }; },
    async saveSettings(parent, studentId, value) { const student = await authorize(parent, studentId); const next = { ...settingsFor(await repositories.getRitualSettings(studentId)), ...value }; if (![next.morningStartHour, next.eveningStartHour].every((hour) => Number.isInteger(hour) && hour >= 0 && hour <= 23) || !Number.isInteger(next.dailySessionLimit) || next.dailySessionLimit < 1 || next.dailySessionLimit > 5 || !['adaptive', 'quest', 'chat', 'activity'].includes(next.preferredStyle) || ![null, 'early', 'explorer', 'independent'].includes(next.experienceBandOverride)) throw new AppError(400, 'VALIDATION_ERROR', 'Choose valid routine controls.'); const saved = settingsFor(await repositories.saveRitualSettings(studentId, next)); return { ...saved, effectiveAgeBand: effectiveAgeBand(student.grade, saved) }; },
    async turn(parent, { sessionId, input, idempotencyKey }) { const session = await repositories.getSession(sessionId); if (!session) throw new AppError(404, 'SESSION_NOT_FOUND', 'Choose a valid learning session.'); const student = await authorize(parent, session.studentId ?? session.student_id); if (!input?.trim()) throw new AppError(400, 'VALIDATION_ERROR', 'A response is required.'); const preflightSafety = checkSafety(input); const personalContact = containsPersonalContact(input); if ((session.endedAt ?? session.ended_at) && !preflightSafety.triggered) throw new AppError(409, 'SESSION_ENDED', 'This check-in has already ended.'); const hash = requestHash(input); const existing = await repositories.getTurnRequest(sessionId, idempotencyKey); if (existing) { if ((existing.requestHash ?? existing.request_hash) !== hash) throw new AppError(409, 'IDEMPOTENCY_MISMATCH', 'This retry key belongs to a different response.'); if (existing.responseBody ?? existing.response_body) return existing.responseBody ?? existing.response_body; throw new AppError(409, 'TURN_IN_PROGRESS', 'This response is still being processed.'); } if (!preflightSafety.triggered && !personalContact) { const current = now(); const from = new Date(Date.UTC(current.getUTCFullYear(), current.getUTCMonth(), current.getUTCDate())); const to = new Date(Date.UTC(current.getUTCFullYear(), current.getUTCMonth(), current.getUTCDate() + 1)); const used = repositories.countHouseholdTurnRequests ? await repositories.countHouseholdTurnRequests(parent.household_id, from, to) : 0; if (used >= config.aiDailyTurnLimit) throw new AppError(429, 'HOUSEHOLD_AI_LIMIT', 'This household has reached its closed-demo AI limit for today.'); } const request = await repositories.createTurnRequest({ sessionId, idempotencyKey, requestHash: hash }); if (!request) throw new AppError(409, 'TURN_IN_PROGRESS', 'This response is still being processed.'); try { const response = await runTurn({ parent, student, session, sessionId, input }); await repositories.completeTurnRequest(request.id, response); return response; } catch (error) { await repositories.removeTurnRequest(request.id); throw error; } }
  });
}
