import { useEffect, useState } from 'react';
import { CompanionMascot, StudentMark } from '#web/shared/components/index.js';
import { getParentMorningRipples, getParentRitualSettings, saveParentRitualSettings } from '#web/features/child-session/index.js';

export function MorningStudio({ student }) {
  const [entries, setEntries] = useState([]); const [settings, setSettings] = useState(null);
  useEffect(() => { getParentMorningRipples(student.id).then((result) => setEntries(result.entries)); getParentRitualSettings(student.id).then(setSettings); }, [student.id]);
  if (!settings) return <section className="portal-panel"><p>Loading Morning Ripple…</p></section>;
  const update = (key, value) => setSettings((current) => ({ ...current, [key]: value }));
  return <section className="portal-grid"><div className="portal-panel wide"><p className="eyebrow">Full daily visibility</p><h1 className="font-display">Morning Ripple studio</h1><div className="control-list"><label><div><strong>Optional AI prompts</strong><p>Curated activities always remain available.</p></div><input type="checkbox" checked={settings.morningAiEnabled} onChange={(event) => update('morningAiEnabled', event.target.checked)} /></label><label><div><strong>Available paths</strong><p>Comma-separated: energy, ready, calm, curiosity, reflect.</p></div><input value={settings.morningPaths} onChange={(event) => update('morningPaths', event.target.value)} /></label><label><div><strong>Content sensitivity</strong><p>Choose the language tone used by the activity deck.</p></div><select value={settings.morningSensitivity} onChange={(event) => update('morningSensitivity', event.target.value)}><option value="standard">Standard</option><option value="gentle">Gentle</option></select></label></div><button className="primary-button" onClick={() => saveParentRitualSettings(student.id, settings).then(setSettings)}>Save Morning Ripple controls</button><div className="reflection-list">{entries.map((entry) => <article key={entry.id}><StudentMark name="spark" size="sm" decorative /><div><strong>{entry.intention}</strong><small>{entry.mood} · {entry.energy} · {entry.path} · {entry.activityResult || 'No extra note'}</small></div><b>{new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric' }).format(new Date(entry.createdAt))}</b></article>)}{!entries.length && <p>No Morning Ripples completed yet.</p>}</div></div><aside className="portal-panel"><CompanionMascot mood="welcome" size="small" decorative /><h2 className="font-display">A record, not a score.</h2><p>Use daily entries to understand the child’s morning, never to judge it.</p></aside></section>;
}
