import { useEffect, useState } from 'react';
import { AppIcon, StudentMark } from '#web/shared/components/index.js';
import { createIdempotencyKey } from '#web/shared/api/index.js';
import { getParentConversation, getParentConversations } from '#web/features/child-session/index.js';
import './conversations.css';
import { clearAdvisorHistory, getAdvisorHistory, getParentTopic, sendAdvisorTurn } from '../api/parentDashboardApi.js';

const stamp = (value) => value ? new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }).format(new Date(value)) : 'Not yet';

export function ConversationsPage({ student }) {
  const [filter, setFilter] = useState('all'); const [conversations, setConversations] = useState([]); const [selected, setSelected] = useState(null); const [detail, setDetail] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const loadList = async () => { try { const result = await getParentConversations(student.id); const next = result.conversations ?? []; setConversations(next); setSelected((current) => next.some((item) => item.id === current) ? current : next[0]?.id ?? null); } catch (issue) { setError(issue.message); } finally { setLoading(false); } };
  const loadDetail = async (sessionId) => { if (!sessionId) return setDetail(null); try { setError(''); setDetail(await getParentConversation(student.id, sessionId)); } catch (issue) { setError(issue.message); } };
  useEffect(() => { setLoading(true); setSelected(null); setDetail(null); loadList(); const interval = window.setInterval(loadList, 10_000); return () => window.clearInterval(interval); }, [student.id]);
  useEffect(() => { loadDetail(selected); }, [selected, student.id]);
  const visible = conversations.filter((item) => filter === 'all' || (filter === 'live' ? item.live : !item.live));
  return <div className="hub-page conversations-page"><header className="hub-page-heading"><p className="hub-kicker">Conversations</p><h1>See each ordinary Pip conversation.</h1><p>Active and finished chats appear here as they are saved. Safety-triggered content is never shown.</p></header><div className="detail-filter" role="group" aria-label="Conversation status"><button className={filter === 'all' ? 'active' : ''} onClick={() => setFilter('all')}>All</button><button className={filter === 'live' ? 'active' : ''} onClick={() => setFilter('live')}>Live now</button><button className={filter === 'completed' ? 'active' : ''} onClick={() => setFilter('completed')}>Completed</button></div><section className="conversation-layout"><div className="conversation-list" aria-busy={loading}>{loading ? <p>Opening conversations…</p> : visible.length ? visible.map((item) => <button key={item.id} className={selected === item.id ? 'active' : ''} onClick={() => setSelected(item.id)}><span className={item.live ? 'conversation-live' : 'conversation-complete'}>{item.live ? 'Live now' : 'Finished'}</span><strong>{item.mode === 'chat' ? 'Talk to Pip' : item.type === 'morning' ? 'Morning Ripple' : 'Evening Discovery'}</strong><small>{stamp(item.endedAt ?? item.startedAt)} · {item.turnCount} turn{item.turnCount === 1 ? '' : 's'}</small></button>) : <div className="hub-empty"><AppIcon name="message" size="lg" decorative /><h2>No conversations here yet.</h2><p>New ordinary chats will appear automatically.</p></div>}</div><aside className="hub-panel conversation-thread" aria-live="polite">{error && <p className="hub-notice">{error}</p>}{detail ? <><div className="conversation-thread-heading"><div><p className="hub-kicker">{detail.conversation.live ? 'Live conversation' : 'Conversation'}</p><h2>{detail.conversation.mode === 'chat' ? 'Talk to Pip' : detail.conversation.type === 'morning' ? 'Morning Ripple' : 'Evening Discovery'}</h2></div>{detail.conversation.live && <span className="conversation-live">Refreshing</span>}</div><div className="conversation-turns">{detail.turns.length ? detail.turns.map((turn) => <article className={turn.role} key={turn.id}><strong>{turn.role === 'companion' ? 'Pip' : 'Your child'}</strong><p>{turn.text}</p><small>{stamp(turn.createdAt)}</small></article>) : <p className="conversation-empty">This conversation is ready for its first saved turn.</p>}</div></> : <div className="hub-empty"><AppIcon name="message" size="lg" decorative /><h2>Choose a conversation.</h2><p>Its saved messages will appear here in order.</p></div>}</aside></section></div>;
}

export function RitualsPage({ data }) {
  const [filter, setFilter] = useState('all');
  const rituals = (data.rituals ?? []).filter((ritual) => filter === 'all' || ritual.type === filter);
  return <div className="hub-page"><header className="hub-page-heading"><p className="hub-kicker">Rituals</p><h1>The small moments that shaped the day.</h1><p>These cards show safe, parent-readable ritual details—not private conversation turns.</p></header><div className="detail-filter" role="group" aria-label="Ritual type"><button className={filter === 'all' ? 'active' : ''} onClick={() => setFilter('all')}>All moments</button><button className={filter === 'morning' ? 'active' : ''} onClick={() => setFilter('morning')}>Morning Ripple</button><button className={filter === 'evening' ? 'active' : ''} onClick={() => setFilter('evening')}>Evening Discovery</button></div><section className="ritual-detail-list">{rituals.length ? rituals.map((ritual) => <article key={`${ritual.type}-${ritual.id}`}><StudentMark name={ritual.collectible ?? (ritual.type === 'morning' ? 'morning' : 'discovery')} size="md" decorative /><div><p className="hub-kicker">{ritual.label} · {stamp(ritual.completedAt)}</p><h2>{ritual.type === 'morning' ? ritual.intention : ritual.title}</h2><p>{ritual.type === 'morning' ? `${ritual.path ? `${ritual.path} path` : 'A gentle start'}${ritual.activity ? ` · ${ritual.activity}` : ''}` : ritual.summary}</p></div></article>) : <div className="hub-empty"><AppIcon name="calendar-clock" size="lg" decorative /><h2>No ritual cards yet.</h2><p>When a moment is complete, a safe summary will appear here.</p></div>}</section></div>;
}

export function LearningPage({ data, student }) {
  const [selected, setSelected] = useState(null);
  const [detail, setDetail] = useState(null);
  const [error, setError] = useState('');
  const choose = async (topic) => { setSelected(topic.id); setDetail(null); setError(''); try { setDetail(await getParentTopic(student.id, topic.id)); } catch (issue) { setError(issue.message); } };
  return <div className="hub-page"><header className="hub-page-heading"><p className="hub-kicker">Learning</p><h1>Ideas to revisit, never scores to chase.</h1><p>Topic signals help you make room for conversation. They do not measure ability, mastery, or performance.</p></header><section className="learning-detail-layout"><div className="topic-detail-list">{(data.learningDetails ?? []).length ? data.learningDetails.map((topic) => <button key={topic.id} className={selected === topic.id ? 'active' : ''} onClick={() => choose(topic)}><span className={`insight-pill ${topic.trend}`}>{topic.trend === 'gentle_revisit' ? 'Revisit kindly' : 'Growing gently'}</span><strong>{topic.label}</strong><small>{topic.signalCount} shared check-in{topic.signalCount === 1 ? '' : 's'} · First noticed {stamp(topic.firstSeenAt)}</small></button>) : <div className="hub-empty"><AppIcon name="compass" size="lg" decorative /><h2>Nothing to interpret yet.</h2><p>Ideas appear here after a child chooses to share them with Pip.</p></div>}</div><aside className="hub-panel topic-detail-card">{error && <p className="hub-notice">{error}</p>}{detail ? <><p className="hub-kicker">Topic detail</p><h2>{detail.label}</h2><p>{detail.signalCount} gentle signal{detail.signalCount === 1 ? '' : 's'} · Last noticed {stamp(detail.lastSeenAt)}</p><p>{detail.reviewReady ? 'This could be a lovely idea to revisit when it feels natural.' : 'There is no need to revisit this idea yet.'}</p><div className="family-prompt-list">{detail.familyPrompts.map((prompt) => <p key={prompt}>“{prompt}”</p>)}</div></> : <><p className="hub-kicker">Pick an idea</p><h2>Open a topic for gentle context.</h2><p>You will see only safe timing, topic, and conversation details here.</p></>}</aside></section></div>;
}

export function AdvisorPage({ student }) {
  const [turns, setTurns] = useState([]); const [input, setInput] = useState(''); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState('');
  const load = () => getAdvisorHistory(student.id).then((result) => setTurns(result.turns ?? [])).catch((error) => setNotice(error.message));
  useEffect(() => { load(); }, [student.id]);
  const ask = async (question = input) => { if (!question.trim() || busy) return; setBusy(true); setNotice(''); try { const result = await sendAdvisorTurn(student.id, { input: question.trim(), idempotencyKey: createIdempotencyKey() }); setTurns((current) => [...current, { id: `parent-${Date.now()}`, role: 'parent', text: question.trim() }, { id: `advisor-${Date.now()}`, role: 'advisor', text: result.message }]); setInput(''); } catch (error) { setNotice(error.message); } finally { setBusy(false); } };
  const clear = async () => { setBusy(true); try { await clearAdvisorHistory(student.id); setTurns([]); setNotice('Advisor history cleared from this parent account.'); } catch (error) { setNotice(error.message); } finally { setBusy(false); } };
  const starters = ['How can I talk about this topic?', 'What is a low-pressure activity for tonight?', 'How can I support a gentle routine?'];
  return <div className="hub-page"><header className="hub-page-heading"><p className="hub-kicker">Ask Pip</p><h1>A calm helper for the grown-ups.</h1><p>Pip uses safe dashboard summaries, not a child’s private words. Suggestions are optional and never diagnoses or evaluations.</p></header><section className="advisor-page"><div className="advisor-starters">{starters.map((starter) => <button key={starter} disabled={busy} onClick={() => ask(starter)}>{starter}</button>)}</div><div className="advisor-transcript" aria-live="polite">{turns.length ? turns.map((turn) => <article key={turn.id} className={turn.role}><strong>{turn.role === 'advisor' ? 'Pip for parents' : 'You'}</strong><p>{turn.text}</p></article>) : <p className="advisor-empty">Ask about routines, a learning topic, or a gentle family conversation.</p>}</div><form className="advisor-form" onSubmit={(event) => { event.preventDefault(); ask(); }}><label className="field-label">Ask Pip for parents<input value={input} maxLength="1200" onChange={(event) => setInput(event.target.value)} placeholder="How can I make space for this idea?" /></label><button className="hub-primary" disabled={busy || !input.trim()}>{busy ? 'Thinking...' : 'Ask Pip'} <AppIcon name="arrow-right" size="xs" decorative /></button></form><div className="advisor-footer"><small>Summary-only context · Parent-only · No child-facing changes</small><button className="hub-secondary" type="button" disabled={busy || !turns.length} onClick={clear}>Clear history</button></div>{notice && <p className="hub-notice" role="status">{notice}</p>}</section></div>;
}
